//////////////////////////////////////////////////
// File autogenerated by buildcounter
// Do not hand edit! (preferably)
//////////////////////////////////////////////////

#ifndef BUILDID_LEVELEDITOR_H
#define BUILDID_LEVELEDITOR_H

const char* GetBuildID_LevelEditor();


#endif //BUILDID_LEVELEDITOR_H
