//////////////////////////////////////////////////
// File autogenerated by buildcounter
// Do not hand edit! (preferably)
//////////////////////////////////////////////////

#ifndef BUILDID_MODELEDITOR_H
#define BUILDID_MODELEDITOR_H

const char* GetBuildID_ModelEditor();


#endif //BUILDID_MODELEDITOR_H
