//////////////////////////////////////////////////
// File autogenerated by buildcounter
// Do not hand edit! (preferably)
//////////////////////////////////////////////////

#ifndef BUILDID_HPL2_0_H
#define BUILDID_HPL2_0_H

const char* GetBuildID_HPL2_0();


#endif //BUILDID_HPL2_0_H
